name: aoc2016
description: Solutions for Advent of Code 2016
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  aoc:
    path: "../aoc"
  collection: ^1.16.0
  crypto: ^3.0.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
