name: aoc2018
description: Solutions for Advent of Code 2018
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  aoc:
    path: "../aoc"
  collection: ^1.15.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
