name: aoc2015
description: Solutions for Advent of Code 2015
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  aoc:
    path: "../aoc"
  collection: ^1.15.0
  crypto: ^3.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
