name: aoc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.4 <4.0.0'

# Add regular dependencies here.
dependencies:
  collection: ^1.17.0
  test: ^1.21.0

dev_dependencies:
  lints: ^2.0.0
